server:
  port: 8080

spring:
  application:
    name: school-management-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    jwt:
      secret: your-256-bit-secret
      expiration: 86400000 # 24 hours

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.school: DEBUG
    org.springframework.security: INFO

app:
  file-storage:
    location: ./uploads
  cors:
    allowed-origins: http://localhost:3000
  notification:
    enabled: true
